server.http2.enabled: true

spring:
  application:
    name: catalog
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      base-path: /management
      exposure.include: '*'
  endpoint:
    health:
      show-details: always
  health:
    probes.enabled: true
    diskspace.enabled: false
    livenessstate.enabled: true
    readinessstate.enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/doc
  swagger-ui:
    url: /openapi.yml

library.catalog:
  data.auto-load:
    enabled: false
    authors.resource: 'classpath:data/catalog-authors.json'
    books.resource: 'classpath:data/catalog-books.json'
    editions.resource: 'classpath:data/catalog-editions.json'
    publishers.resource: 'classpath:data/catalog-publishers.json'

logging:
  level:
    org.adhuc.library.catalog: INFO
    com.atlassian.oai.validator.springmvc: WARN
    org.springframework:
      boot:
        autoconfigure.logging: ERROR
        actuate: ERROR
