branches:
  - name: main
rules:
  minor:
    - feat
  patch:
    - fix
    - refactor
    - chore
    - test
monorepo:
  - name: catalog
    path: ./catalog/
  - name: referencing
    path: ./referencing/
  - name: website
    path: ./website/
  - name: rest-api-support
    path: ./libs/rest-api-support/
