branches:
  - name: main
rules:
  minor:
    - feat
  patch:
    - fix
    - refactor
    - chore
    - test
monorepo:
  - name: catalog
    paths:
      - ./catalog/
      - ./.github/workflows/
  - name: referencing
    paths:
      - ./referencing/
      - ./.github/workflows/
  - name: website
    paths:
      - ./website/
      - ./.github/workflows/
  - name: rest-api-support
    path: ./libs/rest-api-support/
