CATALOG_LOCATION=.

# Defined before inclusions to ensure it is the first target
build: build-catalog ## Build the catalog application

include ./catalog.mk ../common.mk

clean: clean-catalog ## Clean the catalog project folder
