networks:
  website:
    name: website
  observability:
    name: observability

services:
  website:
    container_name: website
    image: website:latest
    ports:
      - 8080
    environment:
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
      SERVER_SSL_KEY_STORE: classpath:ssl/localhost.p12
      SERVER_SSL_KEY_STORE_PASSWORD: password
      SERVER_SSL_KEY_ALIAS: localhost
      SERVER_SSL_KEY_STORE_ENABLED_PROTOCOLS: TLSv1.3
      SPRING_SSL_BUNDLE_JKS_CATALOG_TRUSTSTORE_LOCATION: classpath:ssl/catalog/catalog.p12
      SPRING_SSL_BUNDLE_JKS_CATALOG_TRUSTSTORE_PASSWORD: password
      SPRING_SSL_BUNDLE_JKS_CATALOG_TRUSTSTORE_TYPE: PKCS12
      MANAGEMENT_TRACING_ENABLED: 'true'
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: '1.0'
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      LIBRARY_WEBSITE_REST_CLIENT_CATALOG_BASE_URL: https://catalog:8080
      LIBRARY_WEBSITE_REST_CLIENT_CATALOG_SSL_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/management/health/liveness || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      - website
      - catalog
      - observability
