networks:
  catalog:
    name: catalog

services:
  catalog:
    container_name: catalog
    image: catalog:latest
    ports:
      - 8080
    environment:
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
      SERVER_SSL_KEY_STORE: classpath:ssl/catalog/catalog.p12
      SERVER_SSL_KEY_STORE_PASSWORD: password
      SERVER_SSL_KEY_ALIAS: catalog
      SERVER_SSL_KEY_STORE_ENABLED_PROTOCOLS: TLSv1.3
      LIBRARY_CATALOG_DATA_AUTO_LOAD_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --no-check-certificate --tries=1 --spider https://localhost:8080/management/health/liveness || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      - catalog
