networks:
  website:
    name: website

services:
  website:
    container_name: website
    image: website:latest
    ports:
      - 8080
    environment:
      LIBRARY_WEBSITE_REST_CLIENT_CATALOG_BASE_URL: http://catalog:8080/api/v1
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/management/health/liveness || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      - website
      - catalog
