Feature: Retrieve book details
	As a library member, I want to retrieve book details from the catalog to get information about its author and the
	different editions of the book, and borrow a copy of one of the editions

	Rule: Unknown books cannot be found in the catalog

		Scenario Outline: Fail retrieving unknown book details
			Given Georges is a library member
			When he retrieves the details of a book with ID <bookId> in French
			Then the book details cannot be retrieved because it does not exists
			Examples:
				| bookId                               |
				| edcfece6-93f5-43e4-a15c-a20680d2ddf2 |
				| 967f68ca-e170-439b-9617-5c968ae23ab1 |
				| 31e4ee51-bbf0-4ed1-a54d-b1c0118d2a01 |

	Rule: Books in the catalog have the expected details in the expected language if available and embed their authors

		Scenario Outline: Retrieve known book details
			Given Georges is a library member
			When he retrieves the details of a book with ID <bookId> in <language>
			Then the book details have the expected "<title>", <authors>, "<description>" and wikipedia <link> in the requested <language>
			Examples:
				| bookId                               | language | title                                                          | authors                       | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | link                                                 |
				| b6608a30-1e9b-4ae0-a89d-624c3ca85da4 | French   | Du contrat social                                              | Jean-Jacques Rousseau         | Du contrat social est un traité de philosophie politique présentant comment l’homme, passant de l’état de nature à l’état de société, peut instituer un ordre social au service de l'intérêt commun. Le pacte social que propose Rousseau établit que chacun doit renoncer à tous ses droits particuliers ou du plus fort pour obtenir l'égalité des droits que procure la société. Cette aliénation de chaque sujet de l’État est ce pacte qui offre à chacun l’égalité : « Les clauses [du pacte social] se réduisent toutes à une seule : l’aliénation totale de chaque associé avec tous ses droits à toute la communauté : car premièrement, chacun se donnant tout entier, la condition est égale pour tous ; et la condition étant égale pour tous, nul n’a intérêt de la rendre onéreuse aux autres. » (Livre I, Chapitre 6) La légitimité du pacte social repose sur le fait que l’homme n’aliène pas au sens propre (il ne l'échange pas ni ne le donne) son droit naturel mais il comprend que le pacte social est au contraire la condition de l’existence de ses droits naturels. | https://fr.wikipedia.org/wiki/Du_contrat_social      |
				| 907716df-6a8b-4623-af90-695c1b209df6 | English  | A Feast for Crows                                              | George Raymond Richard Martin | A Feast for Crows is the fourth of seven planned novels in the epic fantasy series A Song of Ice and Fire by American author George R. R. Martin. The novel was first published in the United Kingdom on October 17, 2005, with a United States edition following on November 8, 2005.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | https://en.wikipedia.org/wiki/A_Feast_for_Crows      |
				| 907716df-6a8b-4623-af90-695c1b209df6 | French   | A Feast for Crows                                              | George Raymond Richard Martin | A Feast for Crows (littéralement « Un festin pour les corbeaux ») est le quatrième livre de la saga Le Trône de fer écrite par George R. R. Martin. Le livre a été publié en version originale en 2005, puis en version française de 2006 à 2007. Il se concentre sur les événements se déroulant dans la partie centrale (Conflans, Val d'Arryn, Port-Réal) et méridionale (Bief, Dorne) du continent de Westeros.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | https://fr.wikipedia.org/wiki/A_Feast_for_Crows      |
				| df2c8d87-a334-4c44-9d2b-77c01d172daa | French   | Au commencement était... - Une nouvelle histoire de l'humanité | David Graeber, David Wengrow  | Au commencement était... - Une nouvelle histoire de l'humanité est un livre de l'anthropologue David Graeber et de l'archéologue David Wengrow publié en 2021 aux États-Unis et paru la même année en France aux éditions Les Liens qui libèrent.\n\nEn mettant l'accent sur la diversité des premières sociétés humaines, les auteurs critiquent les récits classiques sur le développement linéaire de l'histoire, du primitivisme à la civilisation. Au commencement était postule au contraire que les humains ont vécu pendant des millénaires au sein de polités vastes et complexes, mais décentralisées. Les auteurs s'appuient sur des preuves archéologiques pour montrer que les premières sociétés étaient diverses et ont développé une grande variété de structures politiques.                                                                                                                                                                                                                                                                                                    | https://fr.wikipedia.org/wiki/Au_commencement_était… |

		Scenario Outline: Retrieve known book without wikipedia link
			Given Georges is a library member
			When he retrieves the details of a book with ID <bookId> in <language>
			Then the book details have no wikipedia link
			Examples:
				| bookId                               | language |
				| 858eba66-6d1a-43fc-be8e-299bc413724a | German   |

		Scenario Outline: Retrieve known book details with default language if none corresponds
			Given Georges is a library member
			When he retrieves the details of a book with ID <bookId> in <language>
			Then the book details have default "<title>" and "<description>" in <defaultLanguage>
			Examples:
				| bookId                               | language | defaultLanguage | title                  | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
				| 858eba66-6d1a-43fc-be8e-299bc413724a | English  | French          | La Horde du Contrevent | La Horde du Contrevent est un roman de science-fantasy écrit par Alain Damasio et publié aux éditions La Volte en 2004. Dans sa première édition, le livre était accompagné d'un CD qui en constituait la « bande originale ». Le roman a été un succès commercial et critique, et a remporté le grand prix de l'Imaginaire en 2006.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
				| 3c25ef66-bc57-4f6e-9b39-6bbfed15a8d6 | German   | English         | Hamlet                 | The Tragedy of Hamlet, Prince of Denmark, often shortened to Hamlet, is a tragedy written by William Shakespeare sometime between 1599 and 1601. It is Shakespeare's longest play. Set in Denmark, the play depicts Prince Hamlet and his attempts to exact revenge against his uncle, Claudius, who has murdered Hamlet's father in order to seize his throne and marry Hamlet's mother. Hamlet is considered among the \"most powerful and influential tragedies in the English language\", with a story capable of \"seemingly endless retelling and adaptation by others.\" It is widely considered one of the greatest plays of all time. Three different early versions of the play are extant: the First Quarto (Q1, 1603); the Second Quarto (Q2, 1604); and the First Folio (F1, 1623). Each version includes lines and passages missing from the others. |
