name: Continuous Delivery pipeline for Library Website
on:
  push:
    branches:
      - 'main'
    paths:
      - 'website/**'
      - '.github/workflows/cd-website.yml'
      - '.github/workflows/cd-generic.yml'
      - '!**/README.md'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
    paths:
      - 'website/**'
      - '.github/workflows/cd-website.yml'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/cd-generic.yml
    with:
      app-name: 'website'
      working-directory: './website'
      github-package: 'library%2Fwebsite'
      docker-image: 'website'
      publish-pacts: true
      run-acceptance: false
    secrets: inherit
